{
  # Instructions for the driver to use.
  "driver": {
    # The name of the driver module under the drivers directory.
    "type": "javascript",

    # The options to pass to the driver.
    "options": {
      # none defined yet.
    },

    # The root directory for all parsing.
    "root": "fixtures/object-define-name-mismatch",

    # For the HTML driver, the HTML file to parse for JavaScript files.
    "pathToHTML": "b/b.html",

    # For the JavaScript driver, the list of raw JavaScript files you want to
    # parse.  Don't use this option if you're going to parse HTML files, or
    # something with a driver pre-defined to load JavaScript files by parsing
    # another source.
    "scripts": [
      "fixture.js"
    ],

    # StackLizard will have bugs.  One example is matching a node that it
    # shouldn't.  See fixtures/object-define-name-mismatch/fixture.js where it
    # calls B.b().  As I write this, StackLizard will normally pick that up and
    # mark it await.  This array is to override StackLizard and tell it to
    # ignore a node.
    "ignore": [
      {

        # The relative path from the root to the source file.
        "path": "fixture.js",

        # The line number of the node.
        "line": 3,

        # The type of the node.
        "type": "CallExpression",

        # If there are multiple nodes on the line of that type, the index of
        # the node to ignore.
        "index": 0,

      }
    ],

    # The actual node to mark asynchronous.
    "markAsync": {

      # The relative path from the root to the source file.
      "path": "fixture.js",

      # The line number of the node.
      "line": 6,

      # If there are multiple nodes on the line of that type, the index of
      # the node to ignore.
      "functionIndex": 0

    },
  },

  "serializer": {
    # The name of the serializer module under the serializers/ directory.
    "type": "markdown",

    # Options to pass into the serializer.
    "options": {

      # The Markdown serializer supports placing caller rows in a child list.
      "nested": true

    }
  }
}
